### PR TITLE
use regex i-flag

### PR DESCRIPTION
**Pull request by amaanq**
ts master supports this now :)

### CODE REVIEW

**Comment by MichaHoffmann** [comment]
Thats so much better! Meaning we can use the tokens again in nvim-treesitter right?

**Review by MichaHoffmann — APPROVED** [review]
Awesome, thank you

**Comment by amaanq** [comment]
hmm, what do you mean by tokens? for matching?

**Comment by MichaHoffmann** [comment]
Yeah, the check in nvim treesitter that broke when i had to do the caseInsensitive hack

**Comment by amaanq** [comment]
you can alias it to a string to match it more easily

`alias(/foo/i, "foo")`

**Comment by MichaHoffmann** [comment]
ah thats good to know! the version you used to generate is not yet released; i would have to generate the grammar with a nightly build of tree-sitter, right?

**Comment by amaanq** [comment]
yep, though we're thinking of releasing a new version soon

**Comment by MichaHoffmann** [comment]
ok; thank you!

**Pull request merged**
